refactor: explanations for interfaces
aeternity/dex-contracts-v2 pull request #54
Opened 2022-03-04 12:03 UTC by bogdan-manole

Closes #39

2022-03-04 12:06 UTC, bogdan-manole commented
Should we change the filename  for contracts/interface/README.md ?

2022-03-04 12:34 UTC, kenodressel commented
Why, whats wrong with the filename?

2022-03-04 12:37 UTC, bogdan-manole commented
> Why, whats wrong with the filename?

I'm just wondering: is it wrong having multiple README.md on different folder levels ?

2022-03-10 10:17 UTC, ghallak requested changes

2022-03-10 10:17 UTC, ghallak commented on contracts/interfaces/README.md
> +- The interfaces from ./for-export are autogenerated and are full contracts definition interface to be
```suggestion
- The interfaces from ./for-export are auto-generated and are full contracts definition interface to be
```

2022-03-10 10:17 UTC, ghallak commented on contracts/interfaces/README.md
> +In js project these can be accessed in the form of `var source = require('dex-contracts-v2/build/INTERFACE_NAME.aes')`
```suggestion
In a JavaScript project these can be accessed in the form of `var source = require('dex-contracts-v2/build/INTERFACE_NAME.aes')`
```

2022-03-10 10:17 UTC, ghallak commented on contracts/interfaces/README.md
> +- The the purpose for the rest of the interfaces is to be used inside this project for tests (js) or inside the contracts.
```suggestion
- The purpose of the rest of the interfaces is to use them inside this project for the tests (JS) or inside the contracts.
```

2022-03-10 10:17 UTC, ghallak commented on contracts/interfaces/README.md
> +We are defining here only the entrypoints that are used and sometime we splitt a contract entrypoints into different interface files
```suggestion
We are defining here only the entrypoints that are used and sometime we split a contract entrypoints into different interface files 
```

2022-03-10 10:17 UTC, ghallak commented on contracts/interfaces/README.md
> +More details you can find it at the top level of these interfaces
```suggestion
You can find further details at the top of each of these interfaces
```

2022-03-10 10:17 UTC, ghallak commented on contracts/interfaces/IAEX9Minimal.aes
> +//Interface for tokens and pair with minimal entrypoints.
```suggestion
// Interface for tokens and pair with minimal entrypoints.
```

2022-03-10 10:17 UTC, ghallak commented on contracts/interfaces/IAEX9Minimal.aes
> +//Interface for tokens and pair with minimal entrypoints.
I don't get what you mean by `pair with minimal entrypoints`.

2022-03-10 19:59 UTC, thepiwo approved these changes

2022-03-11 08:51 UTC, merged